
package ec.stats.ws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StatsWS", targetNamespace = "http://stats.ec/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StatsWS {


    /**
     * 
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMean", targetNamespace = "http://stats.ec/", className = "ec.stats.ws.GetMean")
    @ResponseWrapper(localName = "getMeanResponse", targetNamespace = "http://stats.ec/", className = "ec.stats.ws.GetMeanResponse")
    public double getMean();

    /**
     * 
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMin", targetNamespace = "http://stats.ec/", className = "ec.stats.ws.GetMin")
    @ResponseWrapper(localName = "getMinResponse", targetNamespace = "http://stats.ec/", className = "ec.stats.ws.GetMinResponse")
    public double getMin();

    /**
     * 
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCount", targetNamespace = "http://stats.ec/", className = "ec.stats.ws.GetCount")
    @ResponseWrapper(localName = "getCountResponse", targetNamespace = "http://stats.ec/", className = "ec.stats.ws.GetCountResponse")
    public double getCount();

    /**
     * 
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSTD", targetNamespace = "http://stats.ec/", className = "ec.stats.ws.GetSTD")
    @ResponseWrapper(localName = "getSTDResponse", targetNamespace = "http://stats.ec/", className = "ec.stats.ws.GetSTDResponse")
    public double getSTD();

    /**
     * 
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMax", targetNamespace = "http://stats.ec/", className = "ec.stats.ws.GetMax")
    @ResponseWrapper(localName = "getMaxResponse", targetNamespace = "http://stats.ec/", className = "ec.stats.ws.GetMaxResponse")
    public double getMax();

}
