
package ec.stats.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StatsWSImplService", targetNamespace = "http://stats.ec/", wsdlLocation = "http://localhost:8080/stats-ws/StatsWSImpl?wsdl")
public class StatsWSImplService
    extends Service
{

    private final static URL STATSWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException STATSWSIMPLSERVICE_EXCEPTION;
    private final static QName STATSWSIMPLSERVICE_QNAME = new QName("http://stats.ec/", "StatsWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/stats-ws/StatsWSImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STATSWSIMPLSERVICE_WSDL_LOCATION = url;
        STATSWSIMPLSERVICE_EXCEPTION = e;
    }

    public StatsWSImplService() {
        super(__getWsdlLocation(), STATSWSIMPLSERVICE_QNAME);
    }

    public StatsWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STATSWSIMPLSERVICE_QNAME, features);
    }

    public StatsWSImplService(URL wsdlLocation) {
        super(wsdlLocation, STATSWSIMPLSERVICE_QNAME);
    }

    public StatsWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STATSWSIMPLSERVICE_QNAME, features);
    }

    public StatsWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StatsWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StatsWS
     */
    @WebEndpoint(name = "StatsWSImplPort")
    public StatsWS getStatsWSImplPort() {
        return super.getPort(new QName("http://stats.ec/", "StatsWSImplPort"), StatsWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StatsWS
     */
    @WebEndpoint(name = "StatsWSImplPort")
    public StatsWS getStatsWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://stats.ec/", "StatsWSImplPort"), StatsWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STATSWSIMPLSERVICE_EXCEPTION!= null) {
            throw STATSWSIMPLSERVICE_EXCEPTION;
        }
        return STATSWSIMPLSERVICE_WSDL_LOCATION;
    }

}
